### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GeekYW** [aslanyanhaik/youtube-iOS#1]
Why I open the project , it comes so many errors

**Comment by AF-cgi** [comment]
It's swift 3.

**Comment by GeekYW** [comment]
I open it with Xcode 8.0.

**Comment by GeekYW** [comment]
I konw it's swift 3.0

**Comment by aslanyanhaik** [comment]
@GeekYW please use xCode 8 beta 3 or above

**Comment by GeekYW** [comment]
Thanks

发自 网易邮箱大师
On 08/10/2016 19:05, Haik Aslanyan wrote:

@GeekYW please use xCode 8 beta 3 or above
