### ISSUE TITLE
Auto layouts for view controllers are Not Working

### ISSUE THREAD

**Issue by DineshGurrapu** [aslanyanhaik/youtube-iOS#13]
I am Using this Library like tab bar controller with Different view controllers, When I give constraints for controllers in other view controllers I am not getting the exact Appearnce of that controllers .

**Comment by DineshGurrapu** [comment]
![simulator screen shot 09-jan-2017 4 49 21 pm](https://cloud.githubusercontent.com/assets/19907924/21764907/95d35fd8-d68b-11e6-84a2-92af8a40b840.png)
Like this

Actually I Give Constraints For label ,Center Horizontally,height,width and Top Constraints, but it is Appearing like Above Screen

**Comment by aslanyanhaik** [comment]
Hi @DineshGurrapu you should initialize TabBar UIView to get same functionality. Now the TabBar is not using autolayout, so changing app orientation will cause some issues. But the rest should work
