### ISSUE TITLE
Domain where images and other information is pulled from is down

### ISSUE THREAD

**Issue by hbd** [aslanyanhaik/youtube-iOS#15]
.json files on the domain `http://mexonis.com` are unavailable as the domain is down. These URL's are found in GlobalVariables.swift:

```
home.json
more.json
subscriptions.json
profile.json
video.json
```

Good alternative might be to store those as Gist's

For those who know what the content of the json files were, can you post them here or in a gist?

**Comment by aslanyanhaik** [comment]
yeah I noticed, will update shortly
thanks

**Comment by ghost** [comment]
Is there another location for the files?

**Comment by alexookah** [comment]
can you upload them in another location somewhere?

**Comment by aslanyanhaik** [comment]
Hi everyone, I've pushed a new version with dummy data. Please check
