### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ThePowerOfSwift** [aslanyanhaik/youtube-iOS#3]

**Comment by aslanyanhaik** [comment]
@mihailsalari it was coded by me. However these tutorials helped me lot and I mentioned his name, so people can check other tutorials made by him. Is it an issue to submit codes that someone helped me write?

**Comment by mihailsalari** [comment]
Really? You lie man!

**Comment by aslanyanhaik** [comment]
@mihailsalari Again those tutorials are the reason why I coded this, however I coded in a totally different way, with storyboard, with swift 3, with video player VC etc. I don't seek any profit by uploading codes to github, anyone can watch these tutorials and make this. And I mention author's name and twitter profile so everyone can follow him.  So next time choose words carefully. If there is no other arguments I will close this conversation.

**Comment by mihailsalari** [comment]
https://www.youtube.com/playlist?list=PL0dzCUj1L5JGKdVUtA5xds1zcyzsz7HLj
