### ISSUE TITLE
Why when we hide the navigationbar, the tabbar go to the top automatic?

### ISSUE THREAD

**Issue by roshanman** [aslanyanhaik/youtube-iOS#6]
Why when we hide the navigationbar, the tabbar go to the top automatic?

**Comment by aslanyanhaik** [comment]
@roshanman  sorry for late response. Yes, look for "hideBar" method which is hiding the navigation bar on swipe

**Comment by roshanman** [comment]
Thanks, I have noticed the method hideBar

```
func hideBar(notification: NSNotification)  {
        let state = notification.object as! Bool
        self.navigationController?.setNavigationBarHidden(state, animated: true)
}
```

In this method, we just hide the navigationbar, I don't understand why when we hide the navigationbar, the tabbar go to the top position automatic.

Thank you.

**Comment by aslanyanhaik** [comment]
it's done automatically by iOS. Once you hide the navbar, everything inside the main view goes up with animation.

**Comment by roshanman** [comment]
![record](https://cloud.githubusercontent.com/assets/10202577/20002269/0a1c93e6-a2bb-11e6-814a-378fc9fcd791.gif)

Why my button do not moved when i hide the navbar ?

**Comment by aslanyanhaik** [comment]
Hey @roshanman that's a good question. It depends how you build UI. If your constrains linked with NavBar then it will animate up, otherwise it will not move. Check the attachment. 
[navBar.zip](https://github.com/aslanyanhaik/youtube-iOS/files/574957/navBar.zip)

**Comment by roshanman** [comment]
Thanks for your help. This method worked.

But in your code

```
lazy var tabBar: TabBar = {
    let tb = TabBar.init(frame: CGRect.init(x: 0, y: 0, width: globalVariables.width, height: 64))
    tb.delegate = self
    return tb
}()

//TabBar
self.view.addSubview(self.tabBar)
```

you do have not used constrains for tabbar. really strange!

**Comment by Gerald93** [comment]
Can we make collection view in TabBar to be scrolled if there are many items in TabBar?

**Comment by aslanyanhaik** [comment]
@roshanman  yeah, it was a bad decision. In upcoming update will replace InitWithFrames with constrains
